### ISSUE TITLE
Unable to use in java project ?

### ISSUE THREAD

**Issue by drmkraja** [Dhaval2404/android-form-validation#1]
It shows as NonEmptyRule cannot be resolved...

 .addField(firstNameEt, NonEmptyRule(R.string.error_empty_first_name))

**Comment by Dhaval2404** [comment]
@drmkraja It seems to be working fine for me.

Here is the syntax for Java.

```java
FormValidator.Companion.getInstance()
    .addField(firstNameEt, new NonEmptyRule(R.string.error_empty_first_name))
    .validate();

**Comment by drmkraja** [comment]
Since I'm new to Kotlin, I was Unable to solve it. Now it is working thank you
